version: "3.8"
services:
  teletext:

    # Uncomment when building for prod
    # build: .
    image: arkki/teletext
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - teletext-net
  mongo:
    image: mongo
    expose:
      - "27017"
    networks:
      - teletext-net

networks:
  teletext-net:
    name: teletext-network-ext
    external: false
